### PR TITLE
build: add richhaines preset

### PR DESCRIPTION
**Pull request by molebox**
Hey peeps! 

Id love to add my preset to your awesome list.

og-card-image

### CODE REVIEW

**Comment by Kikobeats** [comment]
hmm, can you check it?

https://cards-git-fork-molebox-rich-haines-preset-microlink.vercel.app/editor?preset=richhaines

not sure what's happening 🤔

**Comment by molebox** [comment]
> hmm, can you check it?
> 
> https://cards-git-fork-molebox-rich-haines-preset-microlink.vercel.app/editor?preset=richhaines
> 
> not sure what's happening 🤔

I think it has something to do with the absolute position i used. I removed it and just used a margin bottom for the same effect. I did notice when adding top: x that an alert popped up and said [object, objetc] but i powered through and ignored it.

Hope it fixed now 😊

**Comment by molebox** [comment]
It was the fragment! I had added the Inline component into it instead of wrapping the whole thing in thwe Inline component. Sorry!

**Comment by Kikobeats** [comment]
awesome 💎

**Pull request merged**
