### PR TITLE
feat: add Monaco editor

### LINKED ISSUE #3: Add editor autocomplete
**Related**

- https://github.com/react-monaco-editor/react-monaco-editor
- https://github.com/sw-yx/awesome-monaco-editor

### PR DESCRIPTION
**Pull request by jletey**
_description coming soon_

Closes #3

### CODE REVIEW

**Comment by jletey** [comment]
Unfortunately I can't view the build logs. Can someone with the correct view rights tell me what's wrong 🙏

**Comment by Kikobeats** [comment]
Hey @jletey thanks a lot for this PR!

I tried to integrate Monaco in the past but the setup was very difficult. `@monaco-editor/react` is doing the integration just a trivial thing 👏

Some questions I want to address:

- First, how did you discover the repo? It's "beta", but happy you discovered it 🙂

Screenshot 2020-04-26 at 16 46 46

- Do you think it could be possible to load a file of "types" in order to give the editor the capability to autocomplete statements?

Screenshot 2020-04-26 at 16 46 02

- Until now the app was using a [set of themes bundled with prism-react-renderer](https://github.com/microlinkhq/cards/blob/master/packages/app/src/theme.js#L6). I guess they are not more longer used and we need to use the themes bundle by monaco editor

**Comment by jletey** [comment]
> * First, how did you discover the repo? It's "beta", but happy you discovered it 🙂

Basically, I was looking through some of [`@peduarte`](https://github.com/peduarte)'s repositories, because I recently discovered [Modulz](https://modulz.app/). I saw that he was using this service for his website, and started looking into it. Really love the idea and wanted to help out :)

> * Do you think it could be possible to load a file of "types" in order to give the editor the capability to autocomplete statements?

Taking a look around, you can create a custom instance of monaco when using `@monaco-editor/react` ([docs](https://github.com/suren-atoyan/monaco-react#monaco-instance)), and this allows you to extend the typings ([playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults)). I'm not entirely quite sure if this will work, but I will start experimenting now :)

> * Until now the app was using a [set of themes bundled with prism-react-renderer](https://github.com/microlinkhq/cards/blob/master/packages/app/src/theme.js#L6). I guess they are not longer used and we need to use the themes bundle by Monaco editor

Yes I was looking into seeing if you can use Prism with Monaco, but it doesn't look trivial. As of right now the Monaco editor only supports two themes (`light` and `dark`), but I'm 99% certain that you can pass in VSCode themes into it.

**Comment by jletey** [comment]
@Kikobeats Sorry for going silent on this 😬Saw that you pushed some changes, what is the plan moving forward?

**Comment by Kikobeats** [comment]
Hey @jletey, I see [monaco-themes](https://github.com/brijeshb42/monaco-themes) could be an easy way to adds more themes into the app, so I'm figuring out a way to connect both parts 🙂

**Comment by jletey** [comment]
@Kikobeats Oh neat great find 👍LMK if you need any help

**Comment by Kikobeats** [comment]
@jletey merged 🎉

I'm happy with the result; still, improvements can be done there, especially defining Monaco Types in order to autocomplete `sx` props although there isn't an affordable way to extends them

**Comment by jletey** [comment]
@Kikobeats Thanks for finishing off my work 😊I'll continue to take a look into extending the typings, and I'll let you know what I find.

**Pull request merged**
