### PR TITLE
feat: Add preset for icon cover card

### PR DESCRIPTION
**Pull request by zdebrine**
The goal here is to allow a user to add a background SVG and an inner icon SVG in the query, which creates a custom icon. 

This card can be used as a cover card of sorts and customized to use any SVG path.

I had initially wanted to pass in the entire SVG object (or even a react component), but ran into issues with sizing.

If you have any ideas on how to clean up the code. Let me know!

Screen Shot 2021-04-27 at 2 34 49 PM

### CODE REVIEW

**Comment by Kikobeats** [comment]
Hey, @zdebrine thanks for that!

Do you need that for a specific user case? are you developing an app or something?

just curiosity 🙂

**Comment by Kikobeats** [comment]
output example

**Comment by zdebrine** [comment]
> Hey, @zdebrine thanks for that!
> 
> Do you need that for a specific user case? are you developing an app or something?
> 
> just curiosity 🙂

@Kikobeats Yeah this is for a somewhat specific use case. I tried using the Screenshot api with microlink, but because this component is behind authentication, I'm unable to just pass in a url and css selector (Because the api would just route to the `/login` page) 

Any ideas on how I could just use the screenshot api and get around authentication?

**Comment by Kikobeats** [comment]
@zdebrine The URL should be publicly reachable in order to make it possible for Microlink API to do the job.

In case you need to authenticate a URL, the thing you can do is to provide the authentication credentials using [headers](https://microlink.io/docs/api/parameters/headers) query parameter.

So for example, if you have control over the backend, you can create a special token that you can pass to Microlink API as headers query parameters for allowing the access bypassing the login page.

Another way could be using [HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication).

with no auth: https://test-http-login.vercel.app/
with auth: https://admin@admin:test-http-login.vercel.app/

makes sense? 🙂

**Comment by Kikobeats** [comment]
still waiting for your reply, @zdebrine!

**Comment by Kikobeats** [comment]
closing because original author doesn't reply :(

**Pull request closed without merging**
